'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const W=require('../game-data/world-boss.js');

function raw(n,cls='guerreiro'){return{userId:'u'+n,charId:'c'+n,name:'Hero'+n,cls,lvl:40,save:{sk:Object.fromEntries(W.CLASS_SKILLS[cls].map(x=>[x,3])),eq:{sword:{atk:55},armor:{def:28,hp:90},cape:{def:12,hp:40},boots:{def:8},jewel:{atk:17,blk:.08}}}}}
function party(){return[raw(1,'guerreiro'),raw(2,'druida'),raw(3,'mago'),raw(4,'arqueiro')].map(W.combatSnapshot)}
function near(i,...ids){for(const id of ids.length?ids:[...i.members.keys()]){const p=i.members.get(id);p.x=i.boss.x-80;p.y=i.boss.y}}
function registration(size=4,owner='u1'){const members=new Map();for(let n=1;n<=size;n++)members.set('u'+n,'Hero'+n);const p={ownerId:'u1',members};return W.validatePartyRegistration({party:p,requesterUserId:owner,activeByUser:id=>{const n=Number(id.slice(1));return n<=4?raw(n):null},bagHasSpace:()=>true})}

test('party exige exatamente 4 e apenas o lider',()=>{for(const n of [1,2,3,5])assert.equal(registration(n).ok,false);assert.equal(registration(4,'u2').ok,false);assert.equal(registration(4).ok,true)});
test('party rejeita offline, char duplicado e mochila sem espaco',()=>{const p={ownerId:'u1',members:new Map([1,2,3,4].map(n=>['u'+n,'H']))};assert.equal(W.validatePartyRegistration({party:p,requesterUserId:'u1',activeByUser:id=>id==='u4'?null:raw(+id.slice(1))}).ok,false);assert.equal(W.validatePartyRegistration({party:p,requesterUserId:'u1',activeByUser:id=>({...raw(+id.slice(1)),charId:'same'})}).ok,false);assert.match(W.validatePartyRegistration({party:p,requesterUserId:'u1',activeByUser:id=>raw(+id.slice(1)),bagHasSpace:()=>false}).error,/mochila/)});
test('snapshot deriva atributos finitos de classe nivel e equipamento',()=>{const p=W.combatSnapshot(raw(1));assert.ok(p.atk>0&&p.def>0&&p.maxHp>0);assert.ok(Object.isFrozen(p));assert.ok(Number.isFinite(W.estimateWorldBossDps(p)))});
test('HP produz TTK deterministico de 300 segundos',()=>{const ps=party(),hp=W.calculateWorldBossHp(ps),dps=ps.reduce((n,p)=>n+W.estimateWorldBossDps(p),0);assert.ok(hp>0&&Number.isFinite(hp));assert.ok(hp/dps>=299&&hp/dps<=301)});
test('mapId e curto isolado e validado por regex',()=>{const a=W.worldBossMapId('world_boss:1790280000000','ABC234'),b=W.worldBossMapId('world_boss:1790280000000','DEF567');assert.match(a,W.WORLD_BOSS_MAP_RE);assert.notEqual(a,b)});
test('duas parties criam bosses e HP independentes',()=>{const a=W.createWorldBossInstance({eventId:'world_boss:1',partyCode:'ABC234',members:party(),now:100}),b=W.createWorldBossInstance({eventId:'world_boss:1',partyCode:'DEF567',members:party(),now:100});near(a,'c1');W.resolveWorldBossDamage(a,'c1',{skill:'basic'},1000,()=>0);assert.notEqual(a.boss.hp,a.boss.maxHp);assert.equal(b.boss.hp,b.boss.maxHp)});
test('msg.atk e contribution forjados sao ignorados',()=>{const i=W.createWorldBossInstance({eventId:'world_boss:1',partyCode:'ABC234',members:party(),now:0});near(i,'c1');const a=W.resolveWorldBossDamage(i,'c1',{skill:'basic',atk:99999,damageContribution:999999},1000,()=>0),j=W.createWorldBossInstance({eventId:'world_boss:1',partyCode:'DEF567',members:party(),now:0});near(j,'c1');const b=W.resolveWorldBossDamage(j,'c1',{skill:'basic',atk:0},1000,()=>0);assert.equal(a.damage,b.damage);assert.equal(i.damageByChar.get('c1'),a.damage)});
test('skill valida classe e cooldown; spam basico e rejeitado',()=>{const i=W.createWorldBossInstance({eventId:'world_boss:1',partyCode:'ABC234',members:party(),now:0});near(i);assert.equal(W.resolveWorldBossDamage(i,'c1',{skill:'fireball'},1000).error,'INVALID_SKILL');assert.equal(W.resolveWorldBossDamage(i,'c1',{skill:'spin'},1000).ok,true);assert.equal(W.resolveWorldBossDamage(i,'c1',{skill:'spin'},1001).error,'COOLDOWN');assert.equal(W.resolveWorldBossDamage(i,'c2',{skill:'basic'},1000).ok,true);assert.equal(W.resolveWorldBossDamage(i,'c2',{skill:'basic'},1001).error,'COOLDOWN')});
test('ataque do boss reduz HP server-side e nunca ultrapassa 35%',()=>{const i=W.createWorldBossInstance({eventId:'world_boss:1',partyCode:'ABC234',members:party(),now:0}),p=i.members.get('c1'),before=p.hp,r=W.applyBossDamage(i,'c1',999999,1000,()=>1);assert.ok(r.damage<=Math.floor(p.maxHp*.35));assert.equal(p.hp,before-r.damage)});
test('Titã possui ataque normal, pesado e AoE telegrafados e esquivaveis por alcance',()=>{assert.deepEqual(Object.keys(W.BOSS_ATTACKS),['normal','heavy','aoe']);assert.equal(W.bossAttackSpec('normal').name,'Golpe do Titã');assert.equal(W.bossAttackSpec('heavy').name,'Impacto Ancestral');assert.equal(W.bossAttackSpec('aoe').name,'Onda Sísmica');for(const spec of Object.values(W.BOSS_ATTACKS)){assert.ok(spec.telegraphMs>=500);assert.ok(spec.range>0);assert.ok(spec.hpRatio<=.35)}});
test('morte marca respawn em 10s sem tocar economia',()=>{const i=W.createWorldBossInstance({eventId:'world_boss:1',partyCode:'ABC234',members:party(),now:0}),p=i.members.get('c1');p.hp=1;const r=W.applyBossDamage(i,'c1',999,5000,()=>1);assert.equal(r.dead,true);assert.equal(r.respawnAt,15000);assert.equal(p.gold,undefined)});
test('disconnect preserva instancia e HP',()=>{const i=W.createWorldBossInstance({eventId:'world_boss:1',partyCode:'ABC234',members:party(),now:0});i.boss.hp-=100;i.members.get('c1').online=false;assert.equal(i.state,'active');assert.equal(i.boss.hp,i.boss.maxHp-100)});
test('morte do boss e sincronica e hits extras nao alteram estado',()=>{const i=W.createWorldBossInstance({eventId:'world_boss:1',partyCode:'ABC234',members:party(),now:0});near(i);i.boss.hp=1;assert.equal(W.resolveWorldBossDamage(i,'c1',{skill:'basic'},1000,()=>0).defeated,true);assert.equal(W.resolveWorldBossDamage(i,'c2',{skill:'basic'},1000).error,'INSTANCE_INACTIVE');assert.equal(i.boss.hp,0)});
test('elegibilidade usa somente dano real minimo de 1%',()=>{const i=W.createWorldBossInstance({eventId:'world_boss:1',partyCode:'ABC234',members:party(),now:0}),need=Math.ceil(i.boss.maxHp*.01);i.damageByChar.set('c1',need);i.damageByChar.set('c2',need-1);assert.deepEqual(W.eligibleMembers(i).map(x=>x.charId),['c1'])});
test('sorteio server-side escolhe exatamente um elegivel com capacidade e faz fallback',()=>{const list=party();assert.equal(W.chooseLegendaryRecipient(list,p=>p.charId!=='c1',()=>0).charId,'c2');assert.equal(W.chooseLegendaryRecipient(list,()=>false,()=>.5),null);assert.equal(W.WORLD_BOSS_REWARD.gold,360);assert.equal(W.WORLD_BOSS_REWARD.gem,18);assert.equal(W.WORLD_BOSS_REWARD.xp,18000)});
test('estado publico expoe HP e party sem identidade interna ou contribuicao',()=>{const i=W.createWorldBossInstance({eventId:'world_boss:1',partyCode:'ABC234',members:party(),now:0}),s=W.publicWorldBossState(i,10);assert.equal(s.boss.type,'ancient_titan');assert.equal(s.party.length,4);assert.equal(JSON.stringify(s).includes('userId'),false);assert.equal('damageByChar' in s,false)});
test('timeout oficial e 10 minutos e respawn 10 segundos',()=>{assert.equal(W.WORLD_BOSS_DURATION_MS,600000);assert.equal(W.WORLD_BOSS_RESPAWN_MS,10000)});
