-- Este arquivo foi substituído por migrations versionadas em
-- supabase/migrations/ (Fase 4). Não edite este arquivo pra mudar o schema
-- -- ele existia como uma "foto" da estrutura final, mas divergia da
-- história real de como o banco foi construído (a tabela `characters`
-- chegou a referenciar auth.users antes de ser corrigida pra
-- public.users, numa migration posterior) e tinha um bug de ordem: definia
-- `characters` referenciando `public.users` antes de `public.users` sequer
-- existir no arquivo -- rodar este arquivo do zero, de cima a baixo, falhava.
--
-- Pra montar o banco do zero (projeto Supabase novo): aplique os arquivos
-- de supabase/migrations/ em ordem (pelo nome, que já é cronológico) --
-- via SQL Editor do Supabase, `supabase db push` (CLI, se configurado), ou
-- a ferramenta `apply_migration` do MCP do Supabase, que é como as 5
-- migrations atuais foram realmente aplicadas em produção.
--
-- Ver "Supabase — migrations" no LEIA-PRIMEIRO.md pra mais detalhes.
